# Base de dados de doenças raras com sintomas, fatores de risco e informações clínicas
# Fontes de referência: OMIM, Orphanet, NORD

DISEASES = [
    {
        "id": "marfan",
        "name": "Síndrome de Marfan",
        "category": "Doença do Tecido Conjuntivo",
        "rarity": "rara",
        "orphanet_code": "ORPHA:558",
        "prevalence": "1:5.000",
        "inheritance": ["autossômica_dominante"],
        "description": "Distúrbio hereditário do tecido conjuntivo que afeta o coração, olhos, vasos sanguíneos e esqueleto.",
        "symptoms": [
            "estatura_alta", "membros_longos", "escoliose", "dor_nas_costas",
            "visao_embaçada", "luxação_do_cristalino", "miopia_grave",
            "palpitações", "dor_no_peito", "sopro_cardíaco",
            "pé_plano", "dedos_longos", "hipermobilidade_articular",
            "tórax_escavado", "tórax_carenado", "fadiga"
        ],
        "family_history_genes": ["FBN1"],
        "family_history_conditions": ["marfan", "aneurisma_aortico", "problemas_cardíacos"],
        "age_of_onset": "qualquer_idade",
        "risk_factors": ["historico_familiar", "sexo_indeterminado"],
        "red_flags": ["aneurisma_aortico", "dissecção_aortica", "luxação_do_cristalino"],
        "urgency": "alta"
    },
    {
        "id": "ehlers_danlos",
        "name": "Síndrome de Ehlers-Danlos",
        "category": "Doença do Tecido Conjuntivo",
        "rarity": "rara",
        "orphanet_code": "ORPHA:98249",
        "prevalence": "1:5.000",
        "inheritance": ["autossômica_dominante", "autossômica_recessiva"],
        "description": "Grupo de distúrbios hereditários do tecido conjuntivo que afetam pele, articulações e paredes dos vasos sanguíneos.",
        "symptoms": [
            "hipermobilidade_articular", "pele_hiperelástica", "cicatrização_lenta",
            "equimoses_frequentes", "dor_crônica", "fadiga", "luxações_frequentes",
            "dor_nas_articulações", "pele_frágil", "feridas_que_não_cicatrizam",
            "dor_muscular", "subluxações", "instabilidade_articular"
        ],
        "family_history_genes": ["COL5A1", "COL5A2", "COL3A1"],
        "family_history_conditions": ["ehlers_danlos", "hipermobilidade", "problemas_articulares"],
        "age_of_onset": "infância_ou_adolescência",
        "risk_factors": ["historico_familiar", "sexo_feminino"],
        "red_flags": ["ruptura_arterial", "ruptura_intestinal"],
        "urgency": "moderada"
    },
    {
        "id": "wilson",
        "name": "Doença de Wilson",
        "category": "Distúrbio Metabólico",
        "rarity": "rara",
        "orphanet_code": "ORPHA:905",
        "prevalence": "1:30.000",
        "inheritance": ["autossômica_recessiva"],
        "description": "Distúrbio genético raro no qual o cobre acumula nos tecidos, causando danos ao fígado, cérebro e outros órgãos.",
        "symptoms": [
            "icterícia", "dor_abdominal", "fadiga", "tremores", "dificuldade_para_falar",
            "dificuldade_para_engolir", "mudanças_de_personalidade", "ansiedade",
            "depressão", "psicose", "anéis_de_kayser_fleischer", "edema",
            "esplenomegalia", "hepatomegalia", "insuficiência_hepática",
            "movimentos_involuntários", "rigidez_muscular", "dificuldade_de_coordenação"
        ],
        "family_history_genes": ["ATP7B"],
        "family_history_conditions": ["wilson", "doença_hepática", "problemas_neurológicos"],
        "age_of_onset": "5_a_35_anos",
        "risk_factors": ["historico_familiar", "consanguinidade"],
        "red_flags": ["insuficiência_hepática_aguda", "anéis_de_kayser_fleischer"],
        "urgency": "alta"
    },
    {
        "id": "pompe",
        "name": "Doença de Pompe",
        "category": "Doença de Depósito Lisossômico",
        "rarity": "ultra_rara",
        "orphanet_code": "ORPHA:365",
        "prevalence": "1:40.000",
        "inheritance": ["autossômica_recessiva"],
        "description": "Doença de depósito de glicogênio causada pela deficiência da enzima alfa-glucosidase ácida, levando ao acúmulo de glicogênio nos músculos.",
        "symptoms": [
            "fraqueza_muscular", "fadiga", "dificuldade_para_respirar",
            "dificuldade_para_engolir", "cardiomegalia", "hepatomegalia",
            "hipotonia", "atraso_no_desenvolvimento_motor", "escoliose",
            "dificuldade_para_caminhar", "quedas_frequentes", "dor_muscular",
            "intolerância_ao_exercício"
        ],
        "family_history_genes": ["GAA"],
        "family_history_conditions": ["pompe", "miopatia", "doença_muscular"],
        "age_of_onset": "qualquer_idade",
        "risk_factors": ["historico_familiar", "consanguinidade"],
        "red_flags": ["insuficiência_respiratória", "cardiomegalia_grave"],
        "urgency": "alta"
    },
    {
        "id": "huntington",
        "name": "Doença de Huntington",
        "category": "Doença Neurodegenerativa",
        "rarity": "rara",
        "orphanet_code": "ORPHA:399",
        "prevalence": "1:10.000",
        "inheritance": ["autossômica_dominante"],
        "description": "Distúrbio cerebral hereditário que causa deterioração progressiva das células nervosas, afetando movimento, cognição e comportamento.",
        "symptoms": [
            "movimentos_involuntários", "coreia", "problemas_de_equilíbrio",
            "dificuldade_para_caminhar", "dificuldade_para_falar", "dificuldade_para_engolir",
            "problemas_de_memória", "declínio_cognitivo", "depressão",
            "ansiedade", "irritabilidade", "impulsividade", "alucinações",
            "insônia", "perda_de_peso", "rigidez_muscular"
        ],
        "family_history_genes": ["HTT"],
        "family_history_conditions": ["huntington", "demência_precoce", "doença_neurológica"],
        "age_of_onset": "30_a_50_anos",
        "risk_factors": ["historico_familiar"],
        "red_flags": ["demência_progressiva_jovem", "coreia"],
        "urgency": "moderada"
    },
    {
        "id": "phenylketonuria",
        "name": "Fenilcetonúria (PKU)",
        "category": "Distúrbio Metabólico",
        "rarity": "rara",
        "orphanet_code": "ORPHA:716",
        "prevalence": "1:10.000",
        "inheritance": ["autossômica_recessiva"],
        "description": "Distúrbio metabólico hereditário em que o organismo não consegue metabolizar adequadamente a fenilalanina.",
        "symptoms": [
            "atraso_no_desenvolvimento_intelectual", "convulsões", "microcefalia",
            "odor_característico", "pele_clara", "cabelos_claros", "olhos_claros",
            "eczema", "hiperatividade", "comportamento_agressivo",
            "atraso_na_fala", "tremores", "problemas_de_postura"
        ],
        "family_history_genes": ["PAH"],
        "family_history_conditions": ["pku", "fenilcetonuria", "deficiência_intelectual"],
        "age_of_onset": "infância",
        "risk_factors": ["historico_familiar", "consanguinidade"],
        "red_flags": ["convulsões_na_infância", "odor_característico"],
        "urgency": "alta"
    },
    {
        "id": "niemann_pick",
        "name": "Doença de Niemann-Pick",
        "category": "Doença de Depósito Lisossômico",
        "rarity": "ultra_rara",
        "orphanet_code": "ORPHA:77292",
        "prevalence": "1:250.000",
        "inheritance": ["autossômica_recessiva"],
        "description": "Grupo de doenças de depósito lipídico que afetam fígado, baço, pulmões, medula óssea e cérebro.",
        "symptoms": [
            "esplenomegalia", "hepatomegalia", "dificuldade_de_aprendizado",
            "perda_de_equilíbrio", "convulsões", "problemas_de_deglutição",
            "movimentos_oculares_anormais", "perda_de_visão", "perda_auditiva",
            "declínio_cognitivo", "ataxia", "distonia", "icterícia_neonatal",
            "dificuldade_para_caminhar", "quedas_frequentes"
        ],
        "family_history_genes": ["NPC1", "NPC2", "SMPD1"],
        "family_history_conditions": ["niemann_pick", "doença_de_depósito"],
        "age_of_onset": "infância_ou_adolescência",
        "risk_factors": ["historico_familiar", "consanguinidade", "ascendência_judaica_ashkenazi"],
        "red_flags": ["oftalmoplegia_supranuclear_vertical", "cataplexia"],
        "urgency": "alta"
    },
    {
        "id": "gaucher",
        "name": "Doença de Gaucher",
        "category": "Doença de Depósito Lisossômico",
        "rarity": "rara",
        "orphanet_code": "ORPHA:355",
        "prevalence": "1:40.000",
        "inheritance": ["autossômica_recessiva"],
        "description": "A doença de depósito lisossômico mais comum, causada pela deficiência da enzima glicocerebrosidase.",
        "symptoms": [
            "esplenomegalia", "hepatomegalia", "anemia", "trombocitopenia",
            "dor_óssea", "fraturas_frequentes", "fadiga", "hematomas_fáceis",
            "sangramento_excessivo", "dor_abdominal", "crescimento_retardado",
            "comprometimento_neurológico", "convulsões"
        ],
        "family_history_genes": ["GBA"],
        "family_history_conditions": ["gaucher", "doença_de_depósito", "anemia_crônica"],
        "age_of_onset": "qualquer_idade",
        "risk_factors": ["historico_familiar", "ascendência_judaica_ashkenazi"],
        "red_flags": ["esplenomegalia_massiva", "crises_ósseas"],
        "urgency": "moderada"
    },
    {
        "id": "fabry",
        "name": "Doença de Fabry",
        "category": "Doença de Depósito Lisossômico",
        "rarity": "ultra_rara",
        "orphanet_code": "ORPHA:324",
        "prevalence": "1:40.000 a 1:117.000",
        "inheritance": ["ligada_ao_x"],
        "description": "Doença de depósito lisossômico ligada ao X causada pela deficiência da enzima alfa-galactosidase A.",
        "symptoms": [
            "dor_nas_extremidades", "intolerância_ao_calor_ou_frio",
            "angiomas_cutâneos", "opacidade_da_córnea", "problemas_renais",
            "hipertensão", "acidente_vascular_cerebral_jovem", "cardiomiopatia",
            "arritmia", "hipoidrose", "diarreia", "dor_abdominal",
            "fadiga", "tinido", "vertigem"
        ],
        "family_history_genes": ["GLA"],
        "family_history_conditions": ["fabry", "doença_renal", "avc_jovem"],
        "age_of_onset": "infância_ou_adolescência",
        "risk_factors": ["historico_familiar", "sexo_masculino"],
        "red_flags": ["avc_em_jovem", "insuficiência_renal_jovem"],
        "urgency": "alta"
    },
    {
        "id": "turner",
        "name": "Síndrome de Turner",
        "category": "Distúrbio Cromossômico",
        "rarity": "rara",
        "orphanet_code": "ORPHA:881",
        "prevalence": "1:2.500 (mulheres)",
        "inheritance": ["cromossômica"],
        "description": "Síndrome cromossômica que afeta mulheres, caracterizada pela ausência parcial ou total de um cromossomo X.",
        "symptoms": [
            "baixa_estatura", "pescoço_alado", "linha_capilar_baixa",
            "orelhas_de_implantação_baixa", "amenorreia", "infertilidade",
            "sopro_cardíaco", "coarctação_da_aorta", "problemas_renais",
            "dificuldade_de_aprendizado", "hipotireoidismo", "osteoporose",
            "linfedema", "unhas_estreitas", "tórax_largo"
        ],
        "family_history_genes": [],
        "family_history_conditions": ["turner"],
        "age_of_onset": "nascimento_ou_infância",
        "risk_factors": ["sexo_feminino"],
        "red_flags": ["amenorreia_primária", "baixa_estatura_extrema"],
        "urgency": "moderada"
    },
    {
        "id": "progeria",
        "name": "Síndrome de Progéria de Hutchinson-Gilford",
        "category": "Distúrbio de Envelhecimento",
        "rarity": "ultra_rara",
        "orphanet_code": "ORPHA:740",
        "prevalence": "1:8.000.000",
        "inheritance": ["autossômica_dominante"],
        "description": "Doença genética extremamente rara que causa envelhecimento acelerado em crianças.",
        "symptoms": [
            "envelhecimento_prematuro", "crescimento_retardado", "perda_de_gordura_corporal",
            "perda_de_cabelo", "pele_enrugada", "voz_aguda",
            "doença_cardiovascular_precoce", "ossos_frágeis", "articulações_rígidas",
            "rosto_pequeno", "mandíbula_pequena", "orelhas_proeminentes"
        ],
        "family_history_genes": ["LMNA"],
        "family_history_conditions": ["progeria"],
        "age_of_onset": "infância_precoce",
        "risk_factors": [],
        "red_flags": ["envelhecimento_acelerado_na_infância"],
        "urgency": "alta"
    },
    {
        "id": "acromegaly",
        "name": "Acromegalia",
        "category": "Distúrbio Endócrino",
        "rarity": "rara",
        "orphanet_code": "ORPHA:963",
        "prevalence": "1:20.000",
        "inheritance": ["geralmente_esporádica"],
        "description": "Distúrbio hormonal causado pelo excesso de hormônio do crescimento, geralmente por tumor hipofisário.",
        "symptoms": [
            "crescimento_das_mãos_e_pés", "engrossamento_das_feições",
            "mandíbula_proeminente", "espaçamento_dentário", "voz_grave",
            "hiperhidrose", "fadiga", "dores_articulares", "dores_de_cabeça",
            "problemas_de_visão", "síndrome_do_túnel_do_carpo", "apneia_do_sono",
            "irregularidades_menstruais", "disfunção_erétil", "pele_oleosa_e_grossa"
        ],
        "family_history_genes": ["AIP", "MEN1"],
        "family_history_conditions": ["acromegalia", "tumor_hipofisário", "men1"],
        "age_of_onset": "adulto",
        "risk_factors": ["historico_familiar"],
        "red_flags": ["crescimento_acral_progressivo", "tumor_hipofisário"],
        "urgency": "moderada"
    },
    {
        "id": "stiff_person",
        "name": "Síndrome da Pessoa Rígida",
        "category": "Distúrbio Neurológico Autoimune",
        "rarity": "ultra_rara",
        "orphanet_code": "ORPHA:3198",
        "prevalence": "1:1.000.000",
        "inheritance": ["autoimune"],
        "description": "Distúrbio neurológico raro caracterizado por rigidez muscular progressiva e espasmos musculares dolorosos.",
        "symptoms": [
            "rigidez_muscular", "espasmos_musculares", "dor_muscular",
            "dificuldade_para_caminhar", "postura_curvada", "hipersensibilidade_a_estímulos",
            "ansiedade", "fobia_de_espaços_abertos", "quedas_frequentes",
            "rigidez_lombar", "espasmos_ao_toque_ou_barulho"
        ],
        "family_history_genes": [],
        "family_history_conditions": ["stiff_person", "doenças_autoimunes", "diabetes_tipo1"],
        "age_of_onset": "adulto",
        "risk_factors": ["sexo_feminino", "doenças_autoimunes"],
        "red_flags": ["rigidez_muscular_progressiva", "espasmos_involuntários"],
        "urgency": "moderada"
    },
    {
        "id": "alpha1_antitrypsin",
        "name": "Deficiência de Alfa-1 Antitripsina",
        "category": "Distúrbio Genético",
        "rarity": "rara",
        "orphanet_code": "ORPHA:60",
        "prevalence": "1:2.500",
        "inheritance": ["autossômica_codominante"],
        "description": "Distúrbio genético que aumenta o risco de doença pulmonar e hepática.",
        "symptoms": [
            "falta_de_ar", "chiado_no_peito", "tosse_crônica", "intolerância_ao_exercício",
            "infecções_respiratórias_frequentes", "icterícia", "hepatomegalia",
            "cirrose", "enfisema_precoce", "bronquite_crônica",
            "perda_de_peso", "fadiga"
        ],
        "family_history_genes": ["SERPINA1"],
        "family_history_conditions": ["alfa1", "doença_pulmonar_crônica", "cirrose"],
        "age_of_onset": "adulto_jovem",
        "risk_factors": ["historico_familiar", "tabagismo"],
        "red_flags": ["enfisema_em_não_fumante", "cirrose_jovem"],
        "urgency": "moderada"
    },
    {
        "id": "myasthenia_gravis",
        "name": "Miastenia Grave",
        "category": "Distúrbio Neuromuscular",
        "rarity": "rara",
        "orphanet_code": "ORPHA:589",
        "prevalence": "1:5.000",
        "inheritance": ["autoimune"],
        "description": "Doença autoimune que causa fraqueza e fadiga dos músculos voluntários.",
        "symptoms": [
            "ptose_palpebral", "diplopia", "disfagia", "disartria",
            "fraqueza_muscular", "fadiga_muscular", "fraqueza_facial",
            "dificuldade_para_respirar", "voz_anasalada", "fraqueza_dos_membros",
            "piora_com_esforço", "melhora_com_repouso"
        ],
        "family_history_genes": [],
        "family_history_conditions": ["miastenia", "doenças_autoimunes", "timoma"],
        "age_of_onset": "qualquer_idade",
        "risk_factors": ["sexo_feminino", "doenças_autoimunes", "timoma"],
        "red_flags": ["crise_miastênica", "insuficiência_respiratória"],
        "urgency": "alta"
    },
    {
        "id": "rett",
        "name": "Síndrome de Rett",
        "category": "Distúrbio do Neurodesenvolvimento",
        "rarity": "ultra_rara",
        "orphanet_code": "ORPHA:778",
        "prevalence": "1:10.000 (meninas)",
        "inheritance": ["ligada_ao_x_dominante"],
        "description": "Distúrbio genético grave do neurodesenvolvimento que afeta principalmente meninas, causando regressão após desenvolvimento inicial aparentemente normal.",
        "symptoms": [
            "regressão_no_desenvolvimento", "perda_do_uso_das_mãos",
            "movimentos_estereotipados_das_mãos", "convulsões", "dificuldade_de_comunicação",
            "problemas_de_marcha", "escoliose", "bruxismo", "apneia",
            "hiperventilação", "perda_da_fala", "deficiência_intelectual",
            "microcefalia_adquirida"
        ],
        "family_history_genes": ["MECP2"],
        "family_history_conditions": ["rett"],
        "age_of_onset": "infância_precoce",
        "risk_factors": ["sexo_feminino"],
        "red_flags": ["regressão_em_menina_após_desenvolvimento_normal"],
        "urgency": "alta"
    },
    {
        "id": "porphyria",
        "name": "Porfiria Aguda Intermitente",
        "category": "Distúrbio Metabólico",
        "rarity": "rara",
        "orphanet_code": "ORPHA:79276",
        "prevalence": "1:20.000",
        "inheritance": ["autossômica_dominante"],
        "description": "Distúrbio hereditário do metabolismo das porfirinas que pode causar ataques agudos com dor abdominal intensa.",
        "symptoms": [
            "dor_abdominal_intensa", "náusea", "vômito", "constipação",
            "fraqueza_muscular", "paralisia", "neuropatia", "convulsões",
            "confusão_mental", "psicose", "ansiedade", "taquicardia",
            "hipertensão", "urina_avermelhada", "sensibilidade_à_luz"
        ],
        "family_history_genes": ["HMBS"],
        "family_history_conditions": ["porfiria", "ataques_abdominais_inexplicados"],
        "age_of_onset": "adulto_jovem",
        "risk_factors": ["historico_familiar", "sexo_feminino", "uso_de_certos_medicamentos"],
        "red_flags": ["ataques_abdominais_com_urina_escura", "neuropatia_aguda"],
        "urgency": "alta"
    },
    {
        "id": "sickle_cell",
        "name": "Anemia Falciforme",
        "category": "Hemoglobinopatia",
        "rarity": "rara",
        "orphanet_code": "ORPHA:232",
        "prevalence": "variável por etnia",
        "inheritance": ["autossômica_recessiva"],
        "description": "Distúrbio hereditário dos glóbulos vermelhos que causa anemia grave e crises de dor.",
        "symptoms": [
            "anemia", "fadiga", "dor_óssea", "crises_de_dor", "icterícia",
            "esplenomegalia", "infecções_frequentes", "atraso_no_crescimento",
            "acidente_vascular_cerebral", "síndrome_torácica_aguda",
            "priapismo", "úlceras_nos_membros", "retinopatia"
        ],
        "family_history_genes": ["HBB"],
        "family_history_conditions": ["anemia_falciforme", "traço_falciforme", "anemia_hemolítica"],
        "age_of_onset": "infância",
        "risk_factors": ["historico_familiar", "ascendência_africana", "consanguinidade"],
        "red_flags": ["crise_vaso-oclusiva", "síndrome_torácica_aguda", "avc"],
        "urgency": "alta"
    },
    {
        "id": "cystic_fibrosis",
        "name": "Fibrose Cística",
        "category": "Distúrbio Genético Multissistêmico",
        "rarity": "rara",
        "orphanet_code": "ORPHA:586",
        "prevalence": "1:2.500 (caucasianos)",
        "inheritance": ["autossômica_recessiva"],
        "description": "Doença genética grave que afeta principalmente os pulmões e o sistema digestório, causando muco espesso e pegajoso.",
        "symptoms": [
            "tosse_crônica_produtiva", "infecções_respiratórias_frequentes",
            "chiado_no_peito", "falta_de_ar", "má_absorção_intestinal",
            "fezes_gordurosas", "baixo_peso", "atraso_no_crescimento",
            "dedos_em_baqueta", "infertilidade_masculina", "pancreatite_recorrente",
            "suor_muito_salgado", "obstrução_intestinal_neonatal"
        ],
        "family_history_genes": ["CFTR"],
        "family_history_conditions": ["fibrose_cística", "doença_pulmonar_crônica"],
        "age_of_onset": "infância",
        "risk_factors": ["historico_familiar", "consanguinidade"],
        "red_flags": ["ileo_meconial", "insuficiência_pancreática_em_criança"],
        "urgency": "alta"
    },
    {
        "id": "periodic_fever",
        "name": "Síndromes de Febre Periódica (PFAPA/FMF)",
        "category": "Distúrbio Autoinflamatório",
        "rarity": "ultra_rara",
        "orphanet_code": "ORPHA:79154",
        "prevalence": "desconhecida",
        "inheritance": ["autossômica_recessiva", "autossômica_dominante"],
        "description": "Grupo de doenças caracterizadas por episódios recorrentes de febre sem causa infecciosa identificada.",
        "symptoms": [
            "febre_recorrente", "dor_abdominal_recorrente", "dor_no_peito",
            "artrite", "erupção_cutânea", "linfonodomegalia", "aftas",
            "faringite_recorrente", "inflamação_ocular", "peritonite"
        ],
        "family_history_genes": ["MEFV", "MVK", "TNFRSF1A"],
        "family_history_conditions": ["febre_mediterrânea", "febre_periódica", "doenças_autoimunes"],
        "age_of_onset": "infância",
        "risk_factors": ["historico_familiar", "ascendência_mediterrânea"],
        "red_flags": ["amiloidose_renal", "febre_sem_causa"],
        "urgency": "moderada"
    },
]

# Mapa de sintomas em português para chave interna
SYMPTOM_LABELS = {
    "estatura_alta": "Estatura muito alta",
    "membros_longos": "Membros (braços/pernas) anormalmente longos",
    "escoliose": "Escoliose (curvatura da coluna)",
    "dor_nas_costas": "Dor nas costas",
    "visao_embaçada": "Visão embaçada",
    "luxação_do_cristalino": "Luxação do cristalino (deslocamento do olho)",
    "miopia_grave": "Miopia grave",
    "palpitações": "Palpitações cardíacas",
    "dor_no_peito": "Dor no peito",
    "sopro_cardíaco": "Sopro cardíaco",
    "pé_plano": "Pé plano",
    "dedos_longos": "Dedos longos e afilados",
    "hipermobilidade_articular": "Hipermobilidade articular (articulações muito flexíveis)",
    "tórax_escavado": "Tórax escavado (afundado)",
    "tórax_carenado": "Tórax carenado (protuberante)",
    "fadiga": "Fadiga / cansaço extremo",
    "pele_hiperelástica": "Pele extremamente elástica",
    "cicatrização_lenta": "Cicatrização lenta de feridas",
    "equimoses_frequentes": "Hematomas / equimoses frequentes",
    "dor_crônica": "Dor crônica generalizada",
    "luxações_frequentes": "Luxações frequentes",
    "dor_nas_articulações": "Dor nas articulações",
    "pele_frágil": "Pele frágil",
    "feridas_que_não_cicatrizam": "Feridas que não cicatrizam",
    "dor_muscular": "Dor muscular",
    "subluxações": "Subluxações articulares",
    "instabilidade_articular": "Instabilidade articular",
    "icterícia": "Icterícia (pele ou olhos amarelados)",
    "dor_abdominal": "Dor abdominal",
    "tremores": "Tremores",
    "dificuldade_para_falar": "Dificuldade para falar / disartria",
    "dificuldade_para_engolir": "Dificuldade para engolir",
    "mudanças_de_personalidade": "Mudanças de personalidade",
    "ansiedade": "Ansiedade",
    "depressão": "Depressão",
    "psicose": "Psicose / alucinações",
    "anéis_de_kayser_fleischer": "Anéis de Kayser-Fleischer nos olhos",
    "edema": "Edema (inchaço)",
    "esplenomegalia": "Esplenomegalia (baço aumentado)",
    "hepatomegalia": "Hepatomegalia (fígado aumentado)",
    "insuficiência_hepática": "Insuficiência hepática",
    "movimentos_involuntários": "Movimentos involuntários",
    "rigidez_muscular": "Rigidez muscular",
    "dificuldade_de_coordenação": "Dificuldade de coordenação / ataxia",
    "fraqueza_muscular": "Fraqueza muscular",
    "dificuldade_para_respirar": "Dificuldade para respirar",
    "cardiomegalia": "Cardiomegalia (coração aumentado)",
    "hipotonia": "Hipotonia (tônus muscular baixo)",
    "atraso_no_desenvolvimento_motor": "Atraso no desenvolvimento motor",
    "dificuldade_para_caminhar": "Dificuldade para caminhar",
    "quedas_frequentes": "Quedas frequentes",
    "intolerância_ao_exercício": "Intolerância ao exercício",
    "coreia": "Coreia (movimentos involuntários dançantes)",
    "problemas_de_equilíbrio": "Problemas de equilíbrio",
    "problemas_de_memória": "Problemas de memória",
    "declínio_cognitivo": "Declínio cognitivo",
    "irritabilidade": "Irritabilidade",
    "impulsividade": "Impulsividade",
    "alucinações": "Alucinações",
    "insônia": "Insônia",
    "perda_de_peso": "Perda de peso inexplicada",
    "atraso_no_desenvolvimento_intelectual": "Atraso no desenvolvimento intelectual",
    "convulsões": "Convulsões / epilepsia",
    "microcefalia": "Microcefalia",
    "odor_característico": "Odor corporal característico",
    "pele_clara": "Pele muito clara (hipopigmentação)",
    "cabelos_claros": "Cabelos muito claros para a etnia",
    "olhos_claros": "Olhos muito claros para a etnia",
    "eczema": "Eczema / dermatite",
    "hiperatividade": "Hiperatividade",
    "comportamento_agressivo": "Comportamento agressivo",
    "atraso_na_fala": "Atraso na fala",
    "dificuldade_de_aprendizado": "Dificuldade de aprendizado",
    "perda_de_equilíbrio": "Perda de equilíbrio",
    "movimentos_oculares_anormais": "Movimentos oculares anormais",
    "perda_de_visão": "Perda de visão",
    "perda_auditiva": "Perda auditiva",
    "ataxia": "Ataxia (descoordenação)",
    "distonia": "Distonia (contrações musculares involuntárias)",
    "icterícia_neonatal": "Icterícia neonatal prolongada",
    "anemia": "Anemia",
    "trombocitopenia": "Trombocitopenia (plaquetas baixas)",
    "dor_óssea": "Dor óssea",
    "fraturas_frequentes": "Fraturas frequentes",
    "hematomas_fáceis": "Hematomas fáceis",
    "sangramento_excessivo": "Sangramento excessivo",
    "crescimento_retardado": "Crescimento retardado",
    "comprometimento_neurológico": "Comprometimento neurológico",
    "dor_nas_extremidades": "Dor nas mãos e pés (acroparestesia)",
    "intolerância_ao_calor_ou_frio": "Intolerância ao calor ou frio",
    "angiomas_cutâneos": "Angiomas cutâneos (manchas vermelhas na pele)",
    "opacidade_da_córnea": "Opacidade da córnea",
    "problemas_renais": "Problemas renais",
    "hipertensão": "Hipertensão",
    "acidente_vascular_cerebral_jovem": "AVC em pessoa jovem",
    "cardiomiopatia": "Cardiomiopatia",
    "arritmia": "Arritmia cardíaca",
    "hipoidrose": "Hipoidrose (pouco suor)",
    "diarreia": "Diarreia crônica",
    "tinido": "Tinido (zumbido nos ouvidos)",
    "vertigem": "Vertigem",
    "baixa_estatura": "Baixa estatura",
    "pescoço_alado": "Pescoço alado (pterígio do pescoço)",
    "linha_capilar_baixa": "Linha de implantação capilar baixa",
    "orelhas_de_implantação_baixa": "Orelhas de implantação baixa",
    "amenorreia": "Amenorreia (ausência de menstruação)",
    "infertilidade": "Infertilidade",
    "coarctação_da_aorta": "Coarctação da aorta",
    "linfedema": "Linfedema",
    "unhas_estreitas": "Unhas estreitas",
    "tórax_largo": "Tórax largo",
    "envelhecimento_prematuro": "Envelhecimento prematuro",
    "perda_de_gordura_corporal": "Perda de gordura corporal",
    "perda_de_cabelo": "Perda de cabelo / alopecia",
    "pele_enrugada": "Pele enrugada precocemente",
    "voz_aguda": "Voz aguda",
    "doença_cardiovascular_precoce": "Doença cardiovascular precoce",
    "ossos_frágeis": "Ossos frágeis",
    "articulações_rígidas": "Articulações rígidas",
    "crescimento_das_mãos_e_pés": "Crescimento das mãos e pés",
    "engrossamento_das_feições": "Engrossamento das feições faciais",
    "mandíbula_proeminente": "Mandíbula proeminente (prognacia)",
    "espaçamento_dentário": "Espaçamento dentário aumentado",
    "voz_grave": "Voz grave",
    "hiperhidrose": "Hiperhidrose (suor excessivo)",
    "dores_articulares": "Dores articulares",
    "dores_de_cabeça": "Dores de cabeça frequentes",
    "problemas_de_visão": "Problemas de visão",
    "síndrome_do_túnel_do_carpo": "Síndrome do túnel do carpo",
    "apneia_do_sono": "Apneia do sono",
    "irregularidades_menstruais": "Irregularidades menstruais",
    "disfunção_erétil": "Disfunção erétil",
    "pele_oleosa_e_grossa": "Pele oleosa e grossa",
    "espasmos_musculares": "Espasmos musculares",
    "hipersensibilidade_a_estímulos": "Hipersensibilidade a estímulos (som, toque)",
    "postura_curvada": "Postura curvada",
    "rigidez_lombar": "Rigidez lombar",
    "espasmos_ao_toque_ou_barulho": "Espasmos ao toque ou barulho",
    "falta_de_ar": "Falta de ar / dispneia",
    "chiado_no_peito": "Chiado no peito / sibilância",
    "tosse_crônica": "Tosse crônica",
    "infecções_respiratórias_frequentes": "Infecções respiratórias frequentes",
    "cirrose": "Cirrose hepática",
    "enfisema_precoce": "Enfisema pulmonar precoce",
    "bronquite_crônica": "Bronquite crônica",
    "ptose_palpebral": "Ptose palpebral (queda da pálpebra)",
    "diplopia": "Diplopia (visão dupla)",
    "disfagia": "Disfagia (dificuldade de deglutição)",
    "disartria": "Disartria (dificuldade na fala)",
    "fraqueza_facial": "Fraqueza facial",
    "voz_anasalada": "Voz anasalada",
    "fraqueza_dos_membros": "Fraqueza dos membros",
    "piora_com_esforço": "Piora dos sintomas com esforço",
    "melhora_com_repouso": "Melhora dos sintomas com repouso",
    "regressão_no_desenvolvimento": "Regressão no desenvolvimento (perda de habilidades)",
    "perda_do_uso_das_mãos": "Perda do uso propositado das mãos",
    "movimentos_estereotipados_das_mãos": "Movimentos estereotipados das mãos",
    "dificuldade_de_comunicação": "Dificuldade de comunicação",
    "bruxismo": "Bruxismo (ranger de dentes)",
    "apneia": "Apneia (paradas respiratórias)",
    "hiperventilação": "Hiperventilação",
    "perda_da_fala": "Perda da fala",
    "deficiência_intelectual": "Deficiência intelectual",
    "microcefalia_adquirida": "Microcefalia adquirida",
    "dor_abdominal_intensa": "Dor abdominal intensa / crises",
    "náusea": "Náusea",
    "vômito": "Vômito",
    "constipação": "Constipação intestinal",
    "paralisia": "Paralisia",
    "neuropatia": "Neuropatia periférica",
    "confusão_mental": "Confusão mental",
    "taquicardia": "Taquicardia",
    "urina_avermelhada": "Urina avermelhada / escura",
    "sensibilidade_à_luz": "Sensibilidade à luz solar (fotossensibilidade)",
    "crises_de_dor": "Crises de dor",
    "síndrome_torácica_aguda": "Síndrome torácica aguda",
    "priapismo": "Priapismo",
    "úlceras_nos_membros": "Úlceras nas pernas",
    "retinopatia": "Retinopatia",
    "tosse_crônica_produtiva": "Tosse crônica com secreção",
    "má_absorção_intestinal": "Má absorção intestinal",
    "fezes_gordurosas": "Fezes gordurosas / esteatorreia",
    "baixo_peso": "Baixo peso para a idade",
    "dedos_em_baqueta": "Dedos em baqueta (hipocratismo digital)",
    "infertilidade_masculina": "Infertilidade masculina",
    "pancreatite_recorrente": "Pancreatite recorrente",
    "suor_muito_salgado": "Suor muito salgado",
    "obstrução_intestinal_neonatal": "Obstrução intestinal neonatal",
    "febre_recorrente": "Febre recorrente sem causa aparente",
    "dor_abdominal_recorrente": "Dor abdominal recorrente",
    "artrite": "Artrite",
    "erupção_cutânea": "Erupção cutânea / rash",
    "linfonodomegalia": "Linfonodomegalia (gânglios aumentados)",
    "aftas": "Aftas orais frequentes",
    "faringite_recorrente": "Faringite recorrente",
    "inflamação_ocular": "Inflamação ocular",
    "peritonite": "Peritonite",
    "hipotireoidismo": "Hipotireoidismo",
    "osteoporose": "Osteoporose",
}
